spring:
  application:
    name: tour-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://journeyai:journeyai_dev_password@localhost:27017/tour_service_db?authSource=admin}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: tour-service-self-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.Map
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info