spring:
  application:
    name: tour-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://journeyai:journeyai_dev_password@localhost:27017/tour_service_db?authSource=admin}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info